heat_template_version: 2015-04-30
description: Installs Prometheus Mysqld Exporter

parameters:

  server_map:
    type: json
    description: Map of servers to be used with OS::Heat::SoftwareDeploymentGroup

  http_proxy:
    type: string
    description: "HTTP proxy URL"
    default: ''

  https_proxy:
    type: string
    description: "HTTPS proxy URL"
    default: ''

  no_proxy:
    type: string
    description: "Exceptions to proxy configuration"
    default: ''

  download_url:
    type: string
    default: "https://github.com/prometheus/mysqld_exporter/releases/download/v0.10.0/mysqld_exporter-0.10.0.linux-amd64.tar.gz"

  mysql_host:
    type: string
    default: ''

  mysql_user:
    type: string

  mysql_pass:
    type: string
    hidden: true

resources:

  # SOFTWARE CONFIGS

  install:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: { get_file: scripts/ubuntu/mysqld_exporter/1_install.sh }
      inputs:
        - name: DOWNLOAD_URL

  configure:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: { get_file: scripts/ubuntu/mysqld_exporter/2_configure.sh }
      inputs:
        - name: HOST
        - name: USER
        - name: PASS

  # SOFTWARE DEPLOYMENTS

  deploy_install:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      config: { get_resource: install }
      servers: { get_param: server_map }
      signal_transport: HEAT_SIGNAL
      input_values:
        http_proxy: { get_param: http_proxy }
        https_proxy: { get_param: https_proxy }
        no_proxy: { get_param: no_proxy }
        DOWNLOAD_URL: { get_param: download_url }

  deploy_configure:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      config: { get_resource: configure }
      servers: { get_param: server_map }
      signal_transport: HEAT_SIGNAL
      input_values:
        http_proxy: { get_param: http_proxy }
        https_proxy: { get_param: https_proxy }
        no_proxy: { get_param: no_proxy }
        HOST: { get_param: mysql_host }
        USER: { get_param: mysql_user }
        PASS: { get_param: mysql_pass }
    depends_on:
      - deploy_install

outputs:
