heat_template_version: 2015-04-30
description: Installs Prometheus

parameters:

  server_map:
    type: json
    description: Map of servers to be used with OS::Heat::SoftwareDeploymentGroup

  http_proxy:
    type: string
    description: "HTTP proxy URL"
    default: ''

  https_proxy:
    type: string
    description: "HTTPS proxy URL"
    default: ''

  no_proxy:
    type: string
    description: "Exceptions to proxy configuration"
    default: ''

  download_url:
    type: string
    default: "https://github.com/prometheus/prometheus/releases/download/v1.6.1/prometheus-1.6.1.linux-amd64.tar.gz"

resources:

  # SOFTWARE CONFIGS

  install:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: { get_file: scripts/ubuntu/1_install.sh }
      inputs:
        - name: DOWNLOAD_URL

  configure:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: { get_file: scripts/ubuntu/2_configure.sh }

  # SOFTWARE DEPLOYMENTS

  deploy_install:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      config: { get_resource: install }
      servers: { get_param: server_map }
      signal_transport: HEAT_SIGNAL
      input_values:
        http_proxy: { get_param: http_proxy }
        https_proxy: { get_param: https_proxy }
        no_proxy: { get_param: no_proxy }
        DOWNLOAD_URL: { get_param: download_url }

  deploy_configure:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      config: { get_resource: configure }
      servers: { get_param: server_map }
      signal_transport: HEAT_SIGNAL
      input_values:
        http_proxy: { get_param: http_proxy }
        https_proxy: { get_param: https_proxy }
        no_proxy: { get_param: no_proxy }
    depends_on:
      - deploy_install

outputs:
